/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.qlbv.views.screen;

import com.qlbv.model.dao.HoaDonDAO;
import com.qlbv.model.dao.KhachHangDAO;
import com.qlbv.model.dao.NhanVienDAO;
import com.qlbv.model.entities.HoaDon;
import java.awt.Font;
import java.text.DecimalFormat;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author anhhao
 */
public class StatisticPanel extends javax.swing.JPanel {
    
    private DefaultTableModel TableModel;
    private List<HoaDon> dsHoaDon;
    private HoaDonDAO hoaDonDAO;
    private DecimalFormat df = new DecimalFormat("#,### VNĐ");
    private KhachHangDAO khachHangDAO;
    private NhanVienDAO nhanVienDAO;
    
    /**
     * Creates new form Statistic
     */
    public StatisticPanel() {
        initComponents();
        
        rdioNgay.setActionCommand("Ngày");
        rdioThang.setActionCommand("Tháng");
        rdioNam.setActionCommand("Năm");
        
        TableModel = (DefaultTableModel) table_thongke.getModel();
        table_thongke.setModel(TableModel);
        
        table_thongke.getTableHeader().setFont(new Font("Arial", Font.BOLD, 18));
        table_thongke.setFont(new Font("Arial", Font.PLAIN, 16));
        table_thongke.setRowHeight(30); 
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        for (int i = 0; i < table_thongke.getColumnCount(); i++) {
            table_thongke.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        }

        
        hoaDonDAO = new HoaDonDAO();
        khachHangDAO = new KhachHangDAO();
        nhanVienDAO = new NhanVienDAO();
        loadDataToTable();
    }

    private void loadDataToTable(){
        dsHoaDon = hoaDonDAO.layDanhSachHoaDon();
        
        loadTable(dsHoaDon);
    }

    private void timHoaDon(){
        String selectedItem = (String) combo_timKiem.getSelectedItem();
        String text_tim = txt_tim.getText().trim();
        HoaDon hd = null;
        
        if (selectedItem.trim().equals("Mã hóa đơn")) {
            hd = hoaDonDAO.timHoaDonTheoMaHD(text_tim, dsHoaDon);
        } else if (selectedItem.trim().equals("Mã khách hàng")) {
            hd = hoaDonDAO.timHoaDonTheoMaKH(text_tim, dsHoaDon);
        } else if (selectedItem.trim().equals("Mã nhân viên")) {
            hd = hoaDonDAO.timHoaDonTheoMaNV(text_tim, dsHoaDon);
        }
        if(hd == null){
            JOptionPane.showMessageDialog(this, "Không tìm thấy!");
            return;
        }
        TableModel.setRowCount(0);
        Object[] rowData = {
                hd.getMaHD(),
                khachHangDAO.timKhachHang(hd.getMaKH().getMaKH()).getTenKH(),
                nhanVienDAO.timNhanVien(hd.getMaNV().getMaNV()).getTenNV(),
                hd.getNgayTao(),
                df.format(hd.getTongTien())
            };
        TableModel.addRow(rowData);
        lb_tongTien.setText("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        group_radio = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        lb_tieude = new javax.swing.JLabel();
        panel_chucNang = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        txt_tim = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        combo_timKiem = new javax.swing.JComboBox<>();
        btn_Tim = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        combo_Tien = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdioNgay = new javax.swing.JRadioButton();
        rdioThang = new javax.swing.JRadioButton();
        rdioNam = new javax.swing.JRadioButton();
        comboTK = new javax.swing.JComboBox<>();
        btn_ThongKe = new javax.swing.JButton();
        Panel_table = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_thongke = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btn_reset = new javax.swing.JButton();
        lb_tongTien = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lb_tieude.setBackground(new java.awt.Color(255, 255, 255));
        lb_tieude.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lb_tieude.setText("Thống kê ");
        lb_tieude.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        lb_tieude.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        panel_chucNang.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Tìm hóa đơn theo");

        combo_timKiem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        combo_timKiem.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mã hóa đơn", "Mã khách hàng", "Mã nhân viên", " ", " ", " " }));

        btn_Tim.setBackground(new java.awt.Color(0, 153, 255));
        btn_Tim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_Tim.setForeground(new java.awt.Color(255, 255, 255));
        btn_Tim.setText("Tìm");
        btn_Tim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                    .addComponent(txt_tim))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combo_timKiem, 0, 181, Short.MAX_VALUE)
                        .addGap(14, 14, 14))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Tim, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(combo_timKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_tim, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Tim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Sắp xếp"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setText("Sắp xếp theo số tiền");

        combo_Tien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn tiêu chí--", "Tăng dần", "Giảm dần" }));
        combo_Tien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo_TienActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addComponent(combo_Tien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(combo_Tien, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Tiêu chí"));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Thống kê theo");

        rdioNgay.setBackground(new java.awt.Color(255, 255, 255));
        group_radio.add(rdioNgay);
        rdioNgay.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdioNgay.setText("Ngày");
        rdioNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioNgayActionPerformed(evt);
            }
        });

        rdioThang.setBackground(new java.awt.Color(255, 255, 255));
        group_radio.add(rdioThang);
        rdioThang.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdioThang.setText("Tháng");
        rdioThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioThangActionPerformed(evt);
            }
        });

        rdioNam.setBackground(new java.awt.Color(255, 255, 255));
        group_radio.add(rdioNam);
        rdioNam.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rdioNam.setText("Năm");
        rdioNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdioNamActionPerformed(evt);
            }
        });

        comboTK.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Chọn--" }));
        comboTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboTKActionPerformed(evt);
            }
        });

        btn_ThongKe.setBackground(new java.awt.Color(0, 204, 0));
        btn_ThongKe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ThongKe.setForeground(new java.awt.Color(255, 255, 255));
        btn_ThongKe.setText("Thống kê");
        btn_ThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThongKeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboTK, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(rdioNgay)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdioThang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rdioNam)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboTK, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rdioNgay)
                    .addComponent(rdioThang)
                    .addComponent(rdioNam)
                    .addComponent(btn_ThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout panel_chucNangLayout = new javax.swing.GroupLayout(panel_chucNang);
        panel_chucNang.setLayout(panel_chucNangLayout);
        panel_chucNangLayout.setHorizontalGroup(
            panel_chucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_chucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panel_chucNangLayout.setVerticalGroup(
            panel_chucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panel_chucNangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_chucNangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_chucNangLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_chucNang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_tieude, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_tieude, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_chucNang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Panel_table.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_thongke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã hóa đơn", "Khách hàng", "Nhân viên lập hóa đơn", "Ngày tạo", "Tổng tiền"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_thongke);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btn_reset.setBackground(new java.awt.Color(153, 153, 153));
        btn_reset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });

        lb_tongTien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_tongTien.setText("jLabel5");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lb_tongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_reset, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_reset)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(lb_tongTien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout Panel_tableLayout = new javax.swing.GroupLayout(Panel_table);
        Panel_table.setLayout(Panel_tableLayout);
        Panel_tableLayout.setHorizontalGroup(
            Panel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(Panel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        Panel_tableLayout.setVerticalGroup(
            Panel_tableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Panel_tableLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(Panel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Panel_table, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_TimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimActionPerformed
        // TODO add your handling code here:
        timHoaDon();
        txt_tim.setText("");
    }//GEN-LAST:event_btn_TimActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        loadDataToTable();
        txt_tim.setText("");
        group_radio.clearSelection();
        comboTK.removeAllItems();
        comboTK.addItem("--Chọn--");
    }//GEN-LAST:event_btn_resetActionPerformed
    
    private void loadTable(List<HoaDon> dsHoaDons){
        TableModel.setRowCount(0);
        
        for (HoaDon hd : dsHoaDons) {
            Object[] rowData = {
                hd.getMaHD(),
                khachHangDAO.timKhachHang(hd.getMaKH().getMaKH()).getTenKH(),
                nhanVienDAO.timNhanVien(hd.getMaNV().getMaNV()).getTenNV(),
                hd.getNgayTao(),
                df.format(hd.getTongTien())
            };
            TableModel.addRow(rowData);
        }
        table_thongke.revalidate();
        table_thongke.repaint();
        
        lb_tongTien.setText(String.format("%10s %20s", "Tổng tiền:",  df.format(hoaDonDAO.tinhDoanhThu(dsHoaDon))));
    }
    
    private void sapXepTienTangDan(){
        dsHoaDon = hoaDonDAO.sapXepTangTheoTien(dsHoaDon);
        loadTable(dsHoaDon);
    }
    
    private void sapXepTienGiamDan(){
        dsHoaDon = hoaDonDAO.sapXepGiamTheoTien(dsHoaDon);
        loadTable(dsHoaDon);
    }
    
    private void combo_TienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo_TienActionPerformed
        // TODO add your handling code here:
        String selected = (String) combo_Tien.getSelectedItem();
        
        if (selected != null) {
            switch (selected) {
                case "Tăng dần":
                    sapXepTienTangDan();
                    break;
                case "Giảm dần":
                    sapXepTienGiamDan();
                    break;
                default:
                    // Nếu chọn mặc định hoặc không hợp lệ
                    loadDataToTable();
                    break;
            }
        }
    }//GEN-LAST:event_combo_TienActionPerformed

    private void comboTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboTKActionPerformed

    }//GEN-LAST:event_comboTKActionPerformed

    private void rdioNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioNgayActionPerformed
        // TODO add your handling code here:
        comboTK.removeAllItems();
        comboTK.addItem("Hôm nay");
        comboTK.addItem("Hôm qua");

    }//GEN-LAST:event_rdioNgayActionPerformed

    private void thongKeHomNay(){
        dsHoaDon = hoaDonDAO.thongKeHomNay(dsHoaDon);
        loadTable(dsHoaDon);
    }
    
    private void btn_ThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThongKeActionPerformed
        String selected = (String) comboTK.getSelectedItem();

        if (selected != null) {
            if (selected.equals("Hôm nay")) {
                dsHoaDon = hoaDonDAO.thongKeHomNay(dsHoaDon);
                loadTable(dsHoaDon);
            } else if (selected.equals("Hôm qua")) {
                dsHoaDon = hoaDonDAO.thongKeHomQua(dsHoaDon);
                loadTable(dsHoaDon);
            } else if (selected.equals("Tháng này")) {
                dsHoaDon = hoaDonDAO.thongKeThangNay(dsHoaDon);
                loadTable(dsHoaDon);
            } else if (selected.equals("Tháng trước")) {
                dsHoaDon = hoaDonDAO.thongKeThangTruoc(dsHoaDon);
                loadTable(dsHoaDon);
            } else if (selected.matches("\\d{4}")) { // Kiểm tra nếu là năm
                dsHoaDon = hoaDonDAO.thongKeTheoNam(dsHoaDon, Integer.parseInt(selected));
                loadTable(dsHoaDon);
            } else {
                loadDataToTable();
            }
        }
        
    }//GEN-LAST:event_btn_ThongKeActionPerformed

    private void rdioThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioThangActionPerformed
        // TODO add your handling code here:
        comboTK.removeAllItems();
        comboTK.addItem("Tháng này");
        comboTK.addItem("Tháng trước");
    }//GEN-LAST:event_rdioThangActionPerformed

    private void rdioNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdioNamActionPerformed
        // TODO add your handling code here:
        comboTK.removeAllItems();
        comboTK.addItem("2025");
        comboTK.addItem("2024");
        comboTK.addItem("2023");
    }//GEN-LAST:event_rdioNamActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Panel_table;
    private javax.swing.JButton btn_ThongKe;
    private javax.swing.JButton btn_Tim;
    private javax.swing.JButton btn_reset;
    private javax.swing.JComboBox<String> comboTK;
    private javax.swing.JComboBox<String> combo_Tien;
    private javax.swing.JComboBox<String> combo_timKiem;
    private javax.swing.ButtonGroup group_radio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_tieude;
    private javax.swing.JLabel lb_tongTien;
    private javax.swing.JPanel panel_chucNang;
    private javax.swing.JRadioButton rdioNam;
    private javax.swing.JRadioButton rdioNgay;
    private javax.swing.JRadioButton rdioThang;
    private javax.swing.JTable table_thongke;
    private javax.swing.JTextField txt_tim;
    // End of variables declaration//GEN-END:variables
}
